apiVersion: v1
kind: Secret
metadata:
  name: dockerconfigjson
  namespace: cinemaabyss
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJjci5zZWxjbG91ZC5ydSI6IHsKCQkJImF1dGgiOiAiZEc5clpXNDZRMUpuUVVGQlFVRlljMDFzTlZSU1QxVmljbVJ6ZVZoV05rUlRlRWg1WVdwdGF6bEhaWGMwT0E9PSIKCQl9LAoJCSJnaGNyLmlvIjogewoJCQkiYXV0aCI6ICJhWEpwYm1GVGEzWTZaMmh3WDBZMk4yc3paMVJrYTBOSk4zSkpUR3RMTWtGd2EyNDJTVEpPY3pSclpqUkxkM1IzVlE9PSIKCQl9Cgl9Cn0=
type: kubernetes.io/dockerconfigjson
